---
logging:
  level:
    root: WARN
nodes:
  node1:
    ip: "localhost"
    port: 8080
  node2:
    ip: "localhost"
    port: 8081
  node3:
    ip: "localhost"
    port: 8082
  node4:
    ip: "localhost"
    port: 8083
  node5:
    ip: "localhost"
    port: 8085
